@host = http://localhost:3000

GET {{host}}/api/products

###
GET {{host}}/api/products/price/950

###
GET {{host}}/api/products/671b89453c3445b535fd408d

###
POST {{host}}/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5ZTIyMmNkYzIzMzMyMmY1NmI5MTYiLCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5MTg3NzI4fQ.3adO9GvUaaMPMFnYMCMboMwdTMJsDeb_c2jFIbVn2dU

{
    "name": "cafetera",
    "description": "nespreso de muy buena calidad",
    "price": 20.99,
    "department": "hogar",
    "stock": 100,
    "available": true
}

###
PUT {{host}}/api/products/67a605f12ff30d593c69c460
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5YzMwNDk4NGUwZDg1ZmZkZjRjZTEiLCJ1c2VyUm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzkxODQyMTJ9.8xtIoPtS76SrUGqb82is0UGEyskUAtfPTfJNPagYIQk

{
    "stock": 343
}

###
DELETE {{host}}/api/products/671f6f8b2bede92b1af1a39f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5ZTIyMmNkYzIzMzMyMmY1NmI5MTYiLCJ1c2VyUm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzkxODY3NTh9.zpE-FQs5tifXd9nOiwhT3kKwYGZnxQR5E-j_W8LVmho

#############
# API USERS #
#############

POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "lorenzo",
    "email": "lorenzo@gmail.com",
    "password": "12345"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "fran@hotmail.com",
    "password": "12345"
}

###
GET {{host}}/api/users/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5YzI1NTcyZTY2ODhiODExYmUwOTciLCJ1c2VyUm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzkxODkwNTN9.Qlssj5m-rGo9_IY2xp2IvJaR9381VYhgb9nMrOnImOQ