@host = http://localhost:3000
####################
### VER PRODUCTOS###
####################

GET {{host}}/api/products
###

GET {{host}}/api/products/67a8d7f6324d3cbf5165cbd4

##########################

GET {{host}}/api/products/price/1600
###

GET {{host}}/api/products/671f6f8b2bede92b1af1a399

######################
### CREAR PRODUCTO ###
######################
POST {{host}}/api/products
Content-Type: application/json
uthorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5YzMwNDk4NGUwZDg1ZmZkZjRjZTEiLCJ1c2VyUm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzkxODQyMTJ9.8xtIoPtS76SrUGqb82is0UGEyskUAtfPTfJNPagYIQk

{
    "name": "Molinillo de semillas",
    "description": "Molinillo de semillas eléctrico",
    "price": 30,
    "department": "electrodomesticos",
    "stock": 12,
    "available": true
}
###
###########################
### ACTUALIZAR PRODUCTO ###
###########################
PUT {{host}}/api/products/67a606ddd0cee841e90fdd99
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5Yzk0OGIwN2RlZTcwNTE2Y2Q5OWEiLCJpYXQiOjE3MzkxODQyMjJ9.NSbw2Q_3wJzouL9Iw88QVZ7fciUuzaPHzIRecXLp2Eo

{
    "stock": 0,
    "price": 50
}
### 

#########################
### ELIMINAR PRODUCTO ###
#########################
DELETE {{host}}/api/products/67a606ddd0cee841e90fdd99
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5ZTIyZThkNzQ4ZGY4YjBhMTEzMzYiLCJ1c2VyUm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzkyMDQyNDR9.Yqm5NC51_sQgQFvx7Bp4xUnpsjCyw6IRpZC-Oh9_q80




#####################
### ver usuarios ###
#####################


POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "Paco",
    "email": "fra@homail.com",
    "password": "123456"
}
###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "fra@homail.com",
    "password": "123456"
}

#####
GET {{host}}/api/users/porfile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E5Yzk0OGIwN2RlZTcwNTE2Y2Q5OWEiLCJpYXQiOjE3MzkxODQyMjJ9.NSbw2Q_3wJzouL9Iw88QVZ7fciUuzaPHzIRecXLp2Eo
